name       : pdfsam
version    : 3.3.7
release    : 3
source     :
    - https://github.com/torakiki/pdfsam/archive/v3.3.7.tar.gz : 6ebd654b84f5e85a240984aaf22f719f877ee9c9a69370594d5933a486f17cdd
license    : AGPL-3.0-only
component  : office
summary    : PDFsam Basic, a free, open source, multi-platform software designed to
    split, merge, extract pages, mix and rotate PDF files.
description: |
    PDFsam Basic, a free, open source, multi-platform software designed to split, merge, extract pages, mix and rotate PDF files.
builddeps  :
    - apache-maven
    - openjdk-8-devel
    - openjfx-8
rundeps    :
    - openjfx-8
    - openjdk-8
networking : yes
build      : |
    export MAVEN_OPTS="-Dmaven.repo.local=./m2"
    mvn -DskipTests=true -Pbasic-release package
install    : |
    install -Dm 00744 pdfsam-community/target/pdfsam-community-$version.jar $installdir/usr/share/pdfsam/pdfsam-community.jar
    ## icons
    pushd pdfsam-community/src
    for sz in 16 24 32 48 64 96 128 256 512; do
        install -Dm 00644 main/resources/images/community/${sz}x${sz}.png $installdir/usr/share/icons/hicolor/${sz}x${sz}/apps/pdfsam.png
    done
    install -Dm 00644 deb/icon.svg $installdir/usr/share/icons/hicolor/scalable/apps/pdfsam.svg
    install -Dm 00644 main/resources/images/community/splash.gif $installdir/usr/share/pdfsam/resources/splash.gif
    ## etc
    install -Dm 00644 main/etc/logback.xml $installdir/usr/share/pdfsam/etc/logback.xml
    ## desktop entry
    install -Dm 00644 $pkgfiles/pdfsam.desktop $installdir/usr/share/applications/pdfsam.desktop
    ## script
    install -Dm 00755 $pkgfiles/pdfsam.sh $installdir/usr/share/pdfsam/bin/pdfsam.sh
