name       : pdfsam
version    : 4.2.12
release    : 8
source     :
    - https://github.com/torakiki/pdfsam/archive/refs/tags/v4.2.12.tar.gz : ab3f742bf9c04397b79e4acbab68ceb30ccbbb6c88e92ec67eecddc156d8d608
license    : AGPL-3.0-only
component  : office
summary    : PDFsam Basic, a free, open source, multi-platform software designed to split, merge, extract pages, mix and rotate PDF files.
description: |
    PDFsam Basic, a free, open source, multi-platform software designed to split, merge, extract pages, mix and rotate PDF files.
builddeps  :
    - apache-maven
    - openjdk-17
rundeps    :
    - openjdk-17
networking : yes
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-17
    export PATH=$JAVA_HOME/bin:$PATH
setup      : |
    sed 's|http://|https://|' -i pom.xml
build      : |
    export MAVEN_OPTS="-Dmaven.repo.local=./m2"
    mvn -DskipTests=true -Drelease -Dgpg.skip package
install    : |
    install -Dm00644 pdfsam-basic/target/assembled/pdfsam-basic-$version.jar $installdir/usr/share/pdfsam/pdfsam.jar
    install -dm00755 $installdir/usr/share/pdfsam/lib/
    install -Dm00644 pdfsam-basic/target/assembled/lib/* $installdir/usr/share/pdfsam/lib/
    install -Dm00644 pdfsam-basic/src/deb/icon.svg $installdir/usr/share/icons/hicolor/scalable/apps/pdfsam.svg
    install -Dm00755 $pkgfiles/pdfsam.sh $installdir/usr/bin/pdfsam
    install -Dm00644 $pkgfiles/pdfsam.desktop -t $installdir/usr/share/applications
