name       : pdfsam
version    : 3.3.7
release    : 4
source     :
    - https://github.com/torakiki/pdfsam/archive/v3.3.7.tar.gz : 6ebd654b84f5e85a240984aaf22f719f877ee9c9a69370594d5933a486f17cdd
license    : AGPL-3.0-only
component  : office
summary    : PDFsam Basic, a free, open source, multi-platform software designed to
    split, merge, extract pages, mix and rotate PDF files.
description: |
    PDFsam Basic, a free, open source, multi-platform software designed to split, merge, extract pages, mix and rotate PDF files.
builddeps  :
    - apache-maven
    - openjfx-8
rundeps    :
    - openjfx-8
networking : yes
setup      : |
    sed 's|http://|https://|' -i pom.xml
build      : |
    export MAVEN_OPTS="-Dmaven.repo.local=./m2"
    mvn -DskipTests=true -Pbasic-release package
install    : |
    install -Dm00644 pdfsam-community/target/pdfsam-community-$version.jar $installdir/usr/share/pdfsam/pdfsam.jar
    install -Dm00644 pdfsam-community/src/deb/icon.svg $installdir/usr/share/icons/hicolor/scalable/apps/pdfsam.svg
    install -Dm00755 $pkgfiles/pdfsam.sh $installdir/usr/bin/pdfsam
    install -Dm00644 $pkgfiles/pdfsam.desktop -t $installdir/usr/share/applications
